Refactor credentials
estafette/estafette-extension-gcs pull request #2
Opened 2020-09-17 10:51 UTC by vitorarins

2020-09-18 07:30 UTC, JorritSalverda commented on .estafette.yaml
> +    image: golang:1.15.1-alpine3.12
1.15.2 is already out.

2020-09-18 13:07 UTC, klesouza commented on params.go
> +	if len(allowedBuckets) <= 0 {
Maybe this should have the opposite effect? If it's empty, it should fail. So we don't have the issue where it has access to any bucket in a project ( or at least it's harder, you would have to specify all buckets manually)

2020-09-18 14:58 UTC, vitorarins commented on params.go
> +	if len(allowedBuckets) <= 0 {
I was actually following the pattern we have with the injection of credentials for `allowedPipelines`. Where the restriction only comes in place if the `allowedPipelines` is set.

But maybe to increase security on this one makes sense to do it differently.

@JorritSalverda any thoughts?

2020-09-18 15:16 UTC, JorritSalverda requested changes

2020-09-18 15:16 UTC, JorritSalverda commented on gcsCredentials.go
> +	AllowedBuckets        []string `json:"allowedBuckets,omitempty"`
I think we shouldn't leave bucket IAM to estafette, but give the `google-cloud-storage` service account roles on specific buckets instead.

2020-09-18 15:16 UTC, JorritSalverda commented on main.go
> +	credentialsJSON = kingpin.Flag("credentials", "GCS credentials configured at service level, passed in to this trusted extension.").Envar("ESTAFETTE_CREDENTIALS_CLOUD_STORAGE").Required().String()
Can we rename the type to `google-cloud-storage` so this envvar becomes `ESTAFETTE_CREDENTIALS_GOOGLE_CLOUD_STORAGE`?

2020-09-18 15:16 UTC, JorritSalverda commented on params.go
> +	if len(allowedBuckets) <= 0 {
See my remark above on dealing with permissions at google cloud IAM level instead of configuring it in the estafette credentials. Much safer I would say.

2020-09-21 07:36 UTC, vitorarins commented on params.go
> +	if len(allowedBuckets) <= 0 {
Clear :+1: 

Will change it now

2020-09-21 08:08 UTC, JorritSalverda approved these changes
lgtm, as long as we do the merge and promotion in the correct order by first adding the new credential types and set correct permissions on various buckets.

2020-09-22 07:48 UTC, merged